language: node_js
node_js:
  - node
script: yarn build
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file:
      - dist/netcalc.js
      - dist/netcalc.min.js
    on:
      tags: true
cache:
  directories:
    - $HOME/.elm/0.19.0/package
